#!/bin/bash

# Simple script to fix Supabase policies
# Run this in your terminal: chmod +x fix-policies.sh && ./fix-policies.sh

echo "🔧 You need to manually run these SQL commands in your Supabase Dashboard:"
echo ""
echo "1. Go to https://supabase.com/dashboard/project/[your-project-id]/sql"
echo "2. Copy and paste the following SQL commands:"
echo ""
echo "-- DROP EXISTING POLICIES"
echo "DROP POLICY IF EXISTS \"Projects are viewable by members\" ON projects;"
echo "DROP POLICY IF EXISTS \"Projects can be inserted by authenticated users\" ON projects;"
echo "DROP POLICY IF EXISTS \"Projects can be updated by owners and admins\" ON projects;"
echo "DROP POLICY IF EXISTS \"Projects can be deleted by owners\" ON projects;"
echo ""
echo "-- CREATE NEW SAFE POLICIES"
echo "CREATE POLICY \"Projects viewable by members\" ON projects"
echo "    FOR SELECT USING ("
echo "        auth.uid() = owner_id OR"
echo "        auth.role() = 'service_role' OR"
echo "        EXISTS ("
echo "            SELECT 1 FROM project_members"
echo "            WHERE project_members.project_id = projects.id"
echo "            AND project_members.user_id = auth.uid()"
echo "        )"
echo "    );"
echo ""
echo "CREATE POLICY \"Projects insertable by authenticated users\" ON projects"
echo "    FOR INSERT WITH CHECK ("
echo "        auth.uid() IS NOT NULL AND"
echo "        auth.uid() = owner_id"
echo "    );"
echo ""
echo "CREATE POLICY \"Projects updatable by owners and admins\" ON projects"
echo "    FOR UPDATE USING ("
echo "        auth.uid() = owner_id OR"
echo "        auth.role() = 'service_role' OR"
echo "        EXISTS ("
echo "            SELECT 1 FROM project_members"
echo "            WHERE project_members.project_id = projects.id"
echo "            AND project_members.user_id = auth.uid()"
echo "            AND project_members.role IN ('owner', 'admin')"
echo "        )"
echo "    );"
echo ""
echo "CREATE POLICY \"Projects deletable by owners\" ON projects"
echo "    FOR DELETE USING ("
echo "        auth.uid() = owner_id OR"
echo "        auth.role() = 'service_role'"
echo "    );"
echo ""
echo "3. Click 'Run' to execute these commands"
echo "4. The infinite recursion error should be resolved"
echo ""
echo "📝 Note: The budget field has already been removed from the API"
