import {
    Puzzle,
    Palette,
    MessageCircle,
    Monitor,
    FileText,
    Compass,
    PieChart,
    Users,
    Package,
    Projector,
    ShoppingCart,
    Calendar,
    FolderOpen,
    Mail,
    UserCircle,
    Sparkles,
    HelpCircle,
    ShieldCheck,
    Key,
    UserPlus,
    Lock,
    Rocket,
    BarChart,
    Megaphone,
    Gauge,
    Lightbulb,
    Image,
    ListTodo,
    CheckSquare,
    Search,
    Pencil,
    PlusSquare,
    Film,
    Settings,
    CreditCard,
    Building,
    Receipt,
    Home,
    BookOpen,
    Share2,
    Tool,
    Code,
    MoreHorizontal,
    Ban,
    Globe,
    LayoutGrid,
    Type,
    Bell,
    AlertTriangle,
    Loader,
    Bone,
    Tag,
    Clock,
    MousePointer,
    ToggleRight,
    Upload,
    ChevronDown,
    List,
    Footprints,
    Map,
    Award
} from 'lucide-react'

import type { JSX } from 'react'

export type NavigationIcons = Record<string, JSX.Element>

const navigationIcon: NavigationIcons = {
    uiComponents: <Puzzle />,
    common: <Palette />,
    uiCommonButton: <MousePointer />,
    uiCommonGrid: <LayoutGrid />,
    uiCommonTypography: <Type />,
    uiCommonIcons: <Image />,
    feedback: <MessageCircle />,
    uiFeedbackAlert: <AlertTriangle />,
    uiFeedbackDialog: <MessageCircle />,
    uiFeedbackDrawer: <Ban />,
    uiFeedbackProgress: <Loader />,
    uiFeedbackSkeleton: <Bone />,
    uiFeedbackSpinner: <Loader />,
    uiFeedbackToast: <Bell />,
    dataDisplay: <Monitor />,
    uiDataDisplayAvatar: <UserCircle />,
    uiDataDisplayBadge: <Award />,
    uiDataDisplayCalendar: <Calendar />,
    uiDataDisplayCard: <CreditCard />,
    uiDataDisplayTable: <List />,
    uiDataDisplayTag: <Tag />,
    uiDataDisplayTimeline: <Clock />,
    uiDataDisplayTooltip: <MessageCircle />,
    forms: <FileText />,
    uiFormsCheckbox: <CheckSquare />,
    uiFormsDatepicker: <Calendar />,
    uiFormsFormControl: <ListTodo />,
    uiFormsInput: <Type />,
    uiFormsInputGroup: <List />,
    uiFormsRadio: <CheckSquare />,
    uiFormsSegment: <PieChart />,
    uiFormsSelect: <List />,
    uiFormsSwitcher: <ToggleRight />,
    uiFormsTimePicker: <Clock />,
    uiFormsUpload: <Upload />,
    navigation: <Compass />,
    uiNavigationDropdown: <ChevronDown />,
    uiNavigationMenu: <List />,
    uiNavigationPagination: <MoreHorizontal />,
    uiNavigationSteps: <Footprints />,
    uiNavigationTabs: <LayoutGrid />,
    graph: <PieChart />,
    uiGraphChart: <BarChart />,
    uiGraphMaps: <Map />,
    concepts: <Lightbulb />,
    customers: <Users />,
    customerList: <Users />,
    customerEdit: <Pencil />,
    customerCreate: <UserPlus />,
    customerDetails: <UserCircle />,
    products: <Package />,
    productList: <List />,
    productEdit: <Pencil />,
    productCreate: <PlusSquare />,
    projects: <Projector />,
    projectScrumBoard: <LayoutGrid />,
    projectList: <ListTodo />,
    projectDetails: <Search />,
    projectTask: <Calendar />,
    projectIssue: <AlertTriangle />,
    orders: <ShoppingCart />,
    orderList: <List />,
    orderEdit: <Film />,
    ordeDetails: <Search />,
    orderCreate: <PlusSquare />,
    calendar: <Calendar />,
    fileManager: <FolderOpen />,
    mail: <Mail />,
    account: <UserCircle />,
    accountSettings: <Settings />,
    accountActivityLogs: <FileText />,
    accountRoleAndPermission: <Settings />,
    accountPricing: <CreditCard />,
    ai: <Sparkles />,
    aiChat: <MessageCircle />,
    aiImage: <Image />,
    chat: <MessageCircle />,
    helpCenter: <HelpCircle />,
    helpCeterSupportHub: <HelpCircle />,
    helpCeterArticle: <FileText />,
    helpCeterEditArticle: <Pencil />,
    helpCeterManageArticle: <Settings />,
    authentication: <ShieldCheck />,
    signIn: <Key />,
    signUp: <UserPlus />,
    forgotPassword: <Lock />,
    resetPassword: <Key />,
    otpVerification: <ShieldCheck />,
    dashboard: <Gauge />,
    dashboardEcommerce: <ShoppingCart />,
    dashboardProject: <Rocket />,
    dashboardAnalytic: <BarChart />,
    dashboardMarketing: <Megaphone />,
    others: <MoreHorizontal />,
    accessDenied: <Ban />,
    landing: <Home />,
    documentation: <BookOpen />,
    sharedComponentDoc: <Share2 />,
    utilsDoc: <Tool />,
    changeLog: <Code />,
    invoice: <Receipt />,
    invoiceCreate: <PlusSquare />,
    invoiceList: <List />,
    payment: <CreditCard />,
    companySettings: <Building />,
}

export default navigationIcon
